export const Countries = [
    { label: 'Afghanistan', dial_code: '+93', region: 'AF', flag: '🇦🇫' },
    { label: 'Albania', dial_code: '+355', region: 'AL', flag: '🇦🇱' },
    { label: 'Algeria', dial_code: '+213', region: 'DZ', flag: '🇩🇿' },
    { label: 'AmericanSamoa', dial_code: '+1684', region: 'AS', flag: '🇦🇸' },
    { label: 'Andorra', dial_code: '+376', region: 'AD', flag: '🇦🇩' },
    { label: 'Angola', dial_code: '+244', region: 'AO', flag: '🇦🇴' },
    { label: 'Anguilla', dial_code: '+1264', region: 'AI', flag: '🇦🇮' },
    { label: 'Antarctica', dial_code: '+672', region: 'AQ', flag: '🇦🇶' },
    { label: 'Antigua and Barbuda', dial_code: '+1268', region: 'AG', flag: '🇦🇬' },
    { label: 'Argentina', dial_code: '+54', region: 'AR', flag: '🇦🇷' },
    { label: 'Armenia', dial_code: '+374', region: 'AM', flag: '🇦🇲' },
    { label: 'Aruba', dial_code: '+297', region: 'AW', flag: '🇦🇼' },
    { label: 'Australia', dial_code: '+61', region: 'AU', flag: '🇦🇺' },
    { label: 'Austria', dial_code: '+43', region: 'AT', flag: '🇦🇹' },
    { label: 'Azerbaijan', dial_code: '+994', region: 'AZ', flag: '🇦🇿' },
    { label: 'Bahamas', dial_code: '+1242', region: 'BS', flag: '🇧🇸' },
    { label: 'Bahrain', dial_code: '+973', region: 'BH', flag: '🇧🇭' },
    { label: 'Bangladesh', dial_code: '+880', region: 'BD', flag: '🇧🇩' },
    { label: 'Barbados', dial_code: '+1246', region: 'BB', flag: '🇧🇧' },
    { label: 'Belarus', dial_code: '+375', region: 'BY', flag: '🇧🇾' },
    { label: 'Belgium', dial_code: '+32', region: 'BE', flag: '🇧🇪' },
    { label: 'Belize', dial_code: '+501', region: 'BZ', flag: '🇧🇿' },
    { label: 'Benin', dial_code: '+229', region: 'BJ', flag: '🇧🇯' },
    { label: 'Bermuda', dial_code: '+1441', region: 'BM', flag: '🇧🇲' },
    { label: 'Bhutan', dial_code: '+975', region: 'BT', flag: '🇧🇹' },
    { label: 'Bolivia, Plurinational State of', dial_code: '+591', region: 'BO', flag: '🇧🇴' },
    { label: 'Bosnia and Herzegovina', dial_code: '+387', region: 'BA', flag: '🇧🇦' },
    { label: 'Botswana', dial_code: '+267', region: 'BW', flag: '🇧🇼' },
    { label: 'Brazil', dial_code: '+55', region: 'BR', flag: '🇧🇷' },
    { label: 'British Indian Ocean Territory', dial_code: '+246', region: 'IO', flag: '🇮🇴' },
    { label: 'Brunei Darussalam', dial_code: '+673', region: 'BN', flag: '🇧🇳' },
    { label: 'Bulgaria', dial_code: '+359', region: 'BG', flag: '🇧🇬' },
    { label: 'Burkina Faso', dial_code: '+226', region: 'BF', flag: '🇧🇫' },
    { label: 'Burundi', dial_code: '+257', region: 'BI', flag: '🇧🇮' },
    { label: 'Cambodia', dial_code: '+855', region: 'KH', flag: '🇰🇭' },
    { label: 'Cameroon', dial_code: '+237', region: 'CM', flag: '🇨🇲' },
    { label: 'Canada', dial_code: '+1', region: 'CA', flag: '🇨🇦' },
    { label: 'Cape Verde', dial_code: '+238', region: 'CV', flag: '🇨🇻' },
    { label: 'Cayman Islands', dial_code: '+345', region: 'KY', flag: '🇰🇾' },
    { label: 'Central African Republic', dial_code: '+236', region: 'CF', flag: '🇨🇫' },
    { label: 'Chad', dial_code: '+235', region: 'TD', flag: '🇹🇩' },
    { label: 'Chile', dial_code: '+56', region: 'CL', flag: '🇨🇱' },
    { label: 'China', dial_code: '+86', region: 'CN', flag: '🇨🇳' },
    { label: 'Christmas Island', dial_code: '+61', region: 'CX', flag: '🇨🇽' },
    { label: 'Cocos (Keeling) Islands', dial_code: '+61', region: 'CC', flag: '🇨🇨' },
    { label: 'Colombia', dial_code: '+57', region: 'CO', flag: '🇨🇴' },
    { label: 'Comoros', dial_code: '+269', region: 'KM', flag: '🇰🇲' },
    { label: 'Congo', dial_code: '+242', region: 'CG', flag: '🇨🇬' },
    { label: 'Congo, The Democratic Republic of the', dial_code: '+243', region: 'CD', flag: '🇨🇩' },
    { label: 'Cook Islands', dial_code: '+682', region: 'CK', flag: '🇨🇰' },
    { label: 'Costa Rica', dial_code: '+506', region: 'CR', flag: '🇨🇷' },
    { label: "Cote d'Ivoire", dial_code: '+225', region: 'CI', flag: '🇨🇮' },
    { label: 'Croatia', dial_code: '+385', region: 'HR', flag: '🇭🇷' },
    { label: 'Cuba', dial_code: '+53', region: 'CU', flag: '🇨🇺' },
    { label: 'Cyprus', dial_code: '+357', region: 'CY', flag: '🇨🇾' },
    { label: 'Czech Republic', dial_code: '+420', region: 'CZ', flag: '🇨🇿' },
    { label: 'Denmark', dial_code: '+45', region: 'DK', flag: '🇩🇰' },
    { label: 'Djibouti', dial_code: '+253', region: 'DJ', flag: '🇩🇯' },
    { label: 'Dominica', dial_code: '+1767', region: 'DM', flag: '🇩🇲' },
    { label: 'Dominican Republic', dial_code: '+1849', region: 'DO', flag: '🇩🇴' },
    { label: 'Ecuador', dial_code: '+593', region: 'EC', flag: '🇪🇨' },
    { label: 'Egypt', dial_code: '+20', region: 'EG', flag: '🇪🇬' },
    { label: 'El Salvador', dial_code: '+503', region: 'SV', flag: '🇸🇻' },
    { label: 'Equatorial Guinea', dial_code: '+240', region: 'GQ', flag: '🇬🇶' },
    { label: 'Eritrea', dial_code: '+291', region: 'ER', flag: '🇪🇷' },
    { label: 'Estonia', dial_code: '+372', region: 'EE', flag: '🇪🇪' },
    { label: 'Ethiopia', dial_code: '+251', region: 'ET', flag: '🇪🇹' },
    { label: 'Falkland Islands (Malvinas)', dial_code: '+500', region: 'FK', flag: '🇫🇰' },
    { label: 'Faroe Islands', dial_code: '+298', region: 'FO', flag: '🇫🇴' },
    { label: 'Fiji', dial_code: '+679', region: 'FJ', flag: '🇫🇯' },
    { label: 'Finland', dial_code: '+358', region: 'FI', flag: '🇫🇮' },
    { label: 'France', dial_code: '+33', region: 'FR', flag: '🇫🇷' },
    { label: 'French Guiana', dial_code: '+594', region: 'GF', flag: '🇬🇫' },
    { label: 'French Polynesia', dial_code: '+689', region: 'PF', flag: '🇵🇫' },
    { label: 'Gabon', dial_code: '+241', region: 'GA', flag: '🇬🇦' },
    { label: 'Gambia', dial_code: '+220', region: 'GM', flag: '🇬🇲' },
    { label: 'Georgia', dial_code: '+995', region: 'GE', flag: '🇬🇪' },
    { label: 'Germany', dial_code: '+49', region: 'DE', flag: '🇩🇪' },
    { label: 'Ghana', dial_code: '+233', region: 'GH', flag: '🇬🇭' },
    { label: 'Gibraltar', dial_code: '+350', region: 'GI', flag: '🇬🇮' },
    { label: 'Greece', dial_code: '+30', region: 'GR', flag: '🇬🇷' },
    { label: 'Greenland', dial_code: '+299', region: 'GL', flag: '🇬🇱' },
    { label: 'Grenada', dial_code: '+1473', region: 'GD', flag: '🇬🇩' },
    { label: 'Guadeloupe', dial_code: '+590', region: 'GP', flag: '🇬🇵' },
    { label: 'Guam', dial_code: '+1671', region: 'GU', flag: '🇬🇺' },
    { label: 'Guatemala', dial_code: '+502', region: 'GT', flag: '🇬🇹' },
    { label: 'Guernsey', dial_code: '+44', region: 'GG', flag: '🇬🇬' },
    { label: 'Guinea', dial_code: '+224', region: 'GN', flag: '🇬🇳' },
    { label: 'Guinea-Bissau', dial_code: '+245', region: 'GW', flag: '🇬🇼' },
    { label: 'Guyana', dial_code: '+592', region: 'GY', flag: '🇬🇾' },
    { label: 'Haiti', dial_code: '+509', region: 'HT', flag: '🇭🇹' },
    { label: 'Holy See (Vatican City State)', dial_code: '+379', region: 'VA', flag: '🇻🇦' },
    { label: 'Honduras', dial_code: '+504', region: 'HN', flag: '🇭🇳' },
    { label: 'Hong Kong', dial_code: '+852', region: 'HK', flag: '🇭🇰' },
    { label: 'Hungary', dial_code: '+36', region: 'HU', flag: '🇭🇺' },
    { label: 'Iceland', dial_code: '+354', region: 'IS', flag: '🇮🇸' },
    { label: 'India', dial_code: '+91', region: 'IN', flag: '🇮🇳' },
    { label: 'Indonesia', dial_code: '+62', region: 'ID', flag: '🇮🇩' },
    { label: 'Iran, Islamic Republic of', dial_code: '+98', region: 'IR', flag: '🇮🇷' },
    { label: 'Iraq', dial_code: '+964', region: 'IQ', flag: '🇮🇶' },
    { label: 'Ireland', dial_code: '+353', region: 'IE', flag: '🇮🇪' },
    { label: 'Isle of Man', dial_code: '+44', region: 'IM', flag: '🇮🇲' },
    { label: 'Israel', dial_code: '+972', region: 'IL', flag: '🇮🇱' },
    { label: 'Italy', dial_code: '+39', region: 'IT', flag: '🇮🇹' },
    { label: 'Jamaica', dial_code: '+1876', region: 'JM', flag: '🇯🇲' },
    { label: 'Japan', dial_code: '+81', region: 'JP', flag: '🇯🇵' },
    { label: 'Jersey', dial_code: '+44', region: 'JE', flag: '🇯🇪' },
    { label: 'Jordan', dial_code: '+962', region: 'JO', flag: '🇯🇴' },
    { label: 'Kazakhstan', dial_code: '+77', region: 'KZ', flag: '🇰🇿' },
    { label: 'Kenya', dial_code: '+254', region: 'KE', flag: '🇰🇪' },
    { label: 'Kiribati', dial_code: '+686', region: 'KI', flag: '🇰🇮' },
    { label: "Korea, Democratic People's Republic of", dial_code: '+850', region: 'KP', flag: '🇰🇵' },
    { label: 'Korea, Republic of', dial_code: '+82', region: 'KR', flag: '🇰🇷' },
    { label: 'Kuwait', dial_code: '+965', region: 'KW', flag: '🇰🇼' },
    { label: 'Kyrgyzstan', dial_code: '+996', region: 'KG', flag: '🇰🇬' },
    { label: "Lao People's Democratic Republic", dial_code: '+856', region: 'LA', flag: '🇱🇦' },
    { label: 'Latvia', dial_code: '+371', region: 'LV', flag: '🇱🇻' },
    { label: 'Lebanon', dial_code: '+961', region: 'LB', flag: '🇱🇧' },
    { label: 'Lesotho', dial_code: '+266', region: 'LS', flag: '🇱🇸' },
    { label: 'Liberia', dial_code: '+231', region: 'LR', flag: '🇱🇷' },
    { label: 'Libyan Arab Jamahiriya', dial_code: '+218', region: 'LY', flag: '🇱🇾' },
    { label: 'Liechtenstein', dial_code: '+423', region: 'LI', flag: '🇱🇮' },
    { label: 'Lithuania', dial_code: '+370', region: 'LT', flag: '🇱🇹' },
    { label: 'Luxembourg', dial_code: '+352', region: 'LU', flag: '🇱🇺' },
    { label: 'Macao', dial_code: '+853', region: 'MO', flag: '🇲🇴' },
    { label: 'Macedonia, The Former Yugoslav Republic of', dial_code: '+389', region: 'MK', flag: '🇲🇰' },
    { label: 'Madagascar', dial_code: '+261', region: 'MG', flag: '🇲🇬' },
    { label: 'Malawi', dial_code: '+265', region: 'MW', flag: '🇲🇼' },
    { label: 'Malaysia', dial_code: '+60', region: 'MY', flag: '🇲🇾' },
    { label: 'Maldives', dial_code: '+960', region: 'MV', flag: '🇲🇻' },
    { label: 'Mali', dial_code: '+223', region: 'ML', flag: '🇲🇱' },
    { label: 'Malta', dial_code: '+356', region: 'MT', flag: '🇲🇹' },
    { label: 'Marshall Islands', dial_code: '+692', region: 'MH', flag: '🇲🇭' },
    { label: 'Martinique', dial_code: '+596', region: 'MQ', flag: '🇲🇶' },
    { label: 'Mauritania', dial_code: '+222', region: 'MR', flag: '🇲🇷' },
    { label: 'Mauritius', dial_code: '+230', region: 'MU', flag: '🇲🇺' },
    { label: 'Mayotte', dial_code: '+262', region: 'YT', flag: '🇾🇹' },
    { label: 'Mexico', dial_code: '+52', region: 'MX', flag: '🇲🇽' },
    { label: 'Micronesia, Federated States of', dial_code: '+691', region: 'FM', flag: '🇫🇲' },
    { label: 'Moldova, Republic of', dial_code: '+373', region: 'MD', flag: '🇲🇩' },
    { label: 'Monaco', dial_code: '+377', region: 'MC', flag: '🇲🇨' },
    { label: 'Mongolia', dial_code: '+976', region: 'MN', flag: '🇲🇳' },
    { label: 'Montenegro', dial_code: '+382', region: 'ME', flag: '🇲🇪' },
    { label: 'Montserrat', dial_code: '+1664', region: 'MS', flag: '🇲🇸' },
    { label: 'Morocco', dial_code: '+212', region: 'MA', flag: '🇲🇦' },
    { label: 'Mozambique', dial_code: '+258', region: 'MZ', flag: '🇲🇿' },
    { label: 'Myanmar', dial_code: '+95', region: 'MM', flag: '🇲🇲' },
    { label: 'Namibia', dial_code: '+264', region: 'NA', flag: '🇳🇦' },
    { label: 'Nauru', dial_code: '+674', region: 'NR', flag: '🇳🇷' },
    { label: 'Nepal', dial_code: '+977', region: 'NP', flag: '🇳🇵' },
    { label: 'Netherlands', dial_code: '+31', region: 'NL', flag: '🇳🇱' },
    { label: 'Netherlands Antilles', dial_code: '+599', region: 'AN', flag: '🇦🇳' },
    { label: 'New Caledonia', dial_code: '+687', region: 'NC', flag: '🇳🇨' },
    { label: 'New Zealand', dial_code: '+64', region: 'NZ', flag: '🇳🇿' },
    { label: 'Nicaragua', dial_code: '+505', region: 'NI', flag: '🇳🇮' },
    { label: 'Niger', dial_code: '+227', region: 'NE', flag: '🇳🇪' },
    { label: 'Nigeria', dial_code: '+234', region: 'NG', flag: '🇳🇬' },
    { label: 'Niue', dial_code: '+683', region: 'NU', flag: '🇳🇺' },
    { label: 'Norfolk Island', dial_code: '+672', region: 'NF', flag: '🇳🇫' },
    { label: 'Northern Mariana Islands', dial_code: '+1670', region: 'MP', flag: '🇲🇵' },
    { label: 'Norway', dial_code: '+47', region: 'NO', flag: '🇳🇴' },
    { label: 'Oman', dial_code: '+968', region: 'OM', flag: '🇴🇲' },
    { label: 'Pakistan', dial_code: '+92', region: 'PK', flag: '🇵🇰' },
    { label: 'Palau', dial_code: '+680', region: 'PW', flag: '🇵🇼' },
    { label: 'Palestinian Territory, Occupied', dial_code: '+970', region: 'PS', flag: '🇵🇸' },
    { label: 'Panama', dial_code: '+507', region: 'PA', flag: '🇵🇦' },
    { label: 'Papua New Guinea', dial_code: '+675', region: 'PG', flag: '🇵🇬' },
    { label: 'Paraguay', dial_code: '+595', region: 'PY', flag: '🇵🇾' },
    { label: 'Peru', dial_code: '+51', region: 'PE', flag: '🇵🇪' },
    { label: 'Philippines', dial_code: '+63', region: 'PH', flag: '🇵🇭' },
    { label: 'Pitcairn', dial_code: '+872', region: 'PN', flag: '🇵🇳' },
    { label: 'Poland', dial_code: '+48', region: 'PL', flag: '🇵🇱' },
    { label: 'Portugal', dial_code: '+351', region: 'PT', flag: '🇵🇹' },
    { label: 'Puerto Rico', dial_code: '+1939', region: 'PR', flag: '🇵🇷' },
    { label: 'Qatar', dial_code: '+974', region: 'QA', flag: '🇶🇦' },
    { label: 'Romania', dial_code: '+40', region: 'RO', flag: '🇷🇴' },
    { label: 'Russia', dial_code: '+7', region: 'RU', flag: '🇷🇺' },
    { label: 'Rwanda', dial_code: '+250', region: 'RW', flag: '🇷🇼' },
    { label: 'Réunion', dial_code: '+262', region: 'RE', flag: '🇷🇪' },
    { label: 'Saint Barthélemy', dial_code: '+590', region: 'BL', flag: '🇧🇱' },
    { label: 'Saint Helena, Ascension and Tristan Da Cunha', dial_code: '+290', region: 'SH', flag: '🇸🇭' },
    { label: 'Saint Kitts and Nevis', dial_code: '+1869', region: 'KN', flag: '🇰🇳' },
    { label: 'Saint Lucia', dial_code: '+1758', region: 'LC', flag: '🇱🇨' },
    { label: 'Saint Martin', dial_code: '+590', region: 'MF', flag: '🇲🇫' },
    { label: 'Saint Pierre and Miquelon', dial_code: '+508', region: 'PM', flag: '🇵🇲' },
    { label: 'Saint Vincent and the Grenadines', dial_code: '+1784', region: 'VC', flag: '🇻🇨' },
    { label: 'Samoa', dial_code: '+685', region: 'WS', flag: '🇼🇸' },
    { label: 'San Marino', dial_code: '+378', region: 'SM', flag: '🇸🇲' },
    { label: 'Sao Tome and Principe', dial_code: '+239', region: 'ST', flag: '🇸🇹' },
    { label: 'Saudi Arabia', dial_code: '+966', region: 'SA', flag: '🇸🇦' },
    { label: 'Senegal', dial_code: '+221', region: 'SN', flag: '🇸🇳' },
    { label: 'Serbia', dial_code: '+381', region: 'RS', flag: '🇷🇸' },
    { label: 'Seychelles', dial_code: '+248', region: 'SC', flag: '🇸🇨' },
    { label: 'Sierra Leone', dial_code: '+232', region: 'SL', flag: '🇸🇱' },
    { label: 'Singapore', dial_code: '+65', region: 'SG', flag: '🇸🇬' },
    { label: 'Slovakia', dial_code: '+421', region: 'SK', flag: '🇸🇰' },
    { label: 'Slovenia', dial_code: '+386', region: 'SI', flag: '🇸🇮' },
    { label: 'Solomon Islands', dial_code: '+677', region: 'SB', flag: '🇸🇧' },
    { label: 'Somalia', dial_code: '+252', region: 'SO', flag: '🇸🇴' },
    { label: 'South Africa', dial_code: '+27', region: 'ZA', flag: '🇿🇦' },
    { label: 'South Georgia and the South Sandwich Islands', dial_code: '+500', region: 'GS', flag: '🇬🇸' },
    { label: 'Spain', dial_code: '+34', region: 'ES', flag: '🇪🇸' },
    { label: 'Sri Lanka', dial_code: '+94', region: 'LK', flag: '🇱🇰' },
    { label: 'Sudan', dial_code: '+249', region: 'SD', flag: '🇸🇩' },
    { label: 'South Sudan', dial_code: '+211', region: 'SS', flag: '🇸🇸' },
    { label: 'Surilabel', dial_code: '+597', region: 'SR', flag: '🇸🇷' },
    { label: 'Svalbard and Jan Mayen', dial_code: '+47', region: 'SJ', flag: '🇸🇯' },
    { label: 'Swaziland', dial_code: '+268', region: 'SZ', flag: '🇸🇿' },
    { label: 'Sweden', dial_code: '+46', region: 'SE', flag: '🇸🇪' },
    { label: 'Switzerland', dial_code: '+41', region: 'CH', flag: '🇨🇭' },
    { label: 'Syrian Arab Republic', dial_code: '+963', region: 'SY', flag: '🇸🇾' },
    { label: 'Taiwan, Province of China', dial_code: '+886', region: 'TW', flag: '🇹🇼' },
    { label: 'Tajikistan', dial_code: '+992', region: 'TJ', flag: '🇹🇯' },
    { label: 'Tanzania, United Republic of', dial_code: '+255', region: 'TZ', flag: '🇹🇿' },
    { label: 'Thailand', dial_code: '+66', region: 'TH', flag: '🇹🇭' },
    { label: 'Timor-Leste', dial_code: '+670', region: 'TL', flag: '🇹🇱' },
    { label: 'Togo', dial_code: '+228', region: 'TG', flag: '🇹🇬' },
    { label: 'Tokelau', dial_code: '+690', region: 'TK', flag: '🇹🇰' },
    { label: 'Tonga', dial_code: '+676', region: 'TO', flag: '🇹🇴' },
    { label: 'Trinidad and Tobago', dial_code: '+1868', region: 'TT', flag: '🇹🇹' },
    { label: 'Tunisia', dial_code: '+216', region: 'TN', flag: '🇹🇳' },
    { label: 'Turkey', dial_code: '+90', region: 'TR', flag: '🇹🇷' },
    { label: 'Turkmenistan', dial_code: '+993', region: 'TM', flag: '🇹🇲' },
    { label: 'Turks and Caicos Islands', dial_code: '+1649', region: 'TC', flag: '🇹🇨' },
    { label: 'Tuvalu', dial_code: '+688', region: 'TV', flag: '🇹🇻' },
    { label: 'Uganda', dial_code: '+256', region: 'UG', flag: '🇺🇬' },
    { label: 'Ukraine', dial_code: '+380', region: 'UA', flag: '🇺🇦' },
    { label: 'United Arab Emirates', dial_code: '+971', region: 'AE', flag: '🇦🇪' },
    { label: 'United Kingdom', dial_code: '+44', region: 'GB', flag: '🇬🇧' },
    { label: 'United States', dial_code: '+1', region: 'US', flag: '🇺🇸' },
    { label: 'Uruguay', dial_code: '+598', region: 'UY', flag: '🇺🇾' },
    { label: 'Uzbekistan', dial_code: '+998', region: 'UZ', flag: '🇺🇿' },
    { label: 'Vanuatu', dial_code: '+678', region: 'VU', flag: '🇻🇺' },
    { label: 'Venezuela, Bolivarian Republic of', dial_code: '+58', region: 'VE', flag: '🇻🇪' },
    { label: 'Viet Nam', dial_code: '+84', region: 'VN', flag: '🇻🇳' },
    { label: 'Virgin Islands, British', dial_code: '+1284', region: 'VG', flag: '🇻🇬' },
    { label: 'Virgin Islands, U.S.', dial_code: '+1340', region: 'VI', flag: '🇻🇮' },
    { label: 'Wallis and Futuna', dial_code: '+681', region: 'WF', flag: '🇼🇫' },
    { label: 'Yemen', dial_code: '+967', region: 'YE', flag: '🇾🇪' },
    { label: 'Zambia', dial_code: '+260', region: 'ZM', flag: '🇿🇲' },
    { label: 'Zimbabwe', dial_code: '+263', region: 'ZW', flag: '🇿🇼' },
    { label: 'Åland Islands', dial_code: '+358', region: 'AX', flag: '🇦🇽' },
]